### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by follower46** [danthelion/doc2audiobook#1]
I get "TypeError: Type List cannot be instantiated; use list() instead" when running.
I'm not 100% on python typing (I don't use it in any projects) but should ttl_utils.py be:

> def collect_input_files(input_directory_path: Path) -> List[Path]:

not

> def collect_input_files(input_directory_path: Path) -> List(Path):

?

**Comment by danthelion** [comment]
Thanks for the fix (for reference: #2)
